version: '3'

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  cache:
    image: redis:latest
    ports:
      - 6379:6379

  node-app:
    depends_on:
      - db
      - cache
    build: .
    ports:
      - 8080:8080